# Generated by Django 4.2.1 on 2023-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buku",
            fields=[
                ("id_buku", models.AutoField(primary_key=True, serialize=False)),
                ("cover_buku", models.CharField(max_length=500)),
                ("judul_buku", models.CharField(max_length=255)),
                ("stok", models.CharField(max_length=20)),
            ],
        ),
    ]
